blank_issues_enabled: false
contact_links:
  - name: JASP Guide for Requesting Features or Reporting Bugs
    url: https://jasp-stats.org/2018/03/29/request-feature-report-bug-jasp/
    about: Please use one of the templates to request a feature or report a bug
