
# via https://github.com/actions/stale
# 1. label all issues that have a waiting-for-requester label as stale 
#    after 42 days (6 weeks)
# 2. close stale issues after 42 days of inactivity

name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v6
        with:
          stale-issue-message: 'This issue will be automatically closed in 42 days due to inactivity. Feel free to leave a comment if you believe this is still relevant.'
          close-issue-message: 'Automatically closed due to inactivity.'
          operations-per-run: 100
          close-issue-label: 'Stale-closed'
          
          # labels stale all issues with a waiting for requester label:
          any-of-labels: 'waiting for requester'
          days-before-stale: 42
          days-before-close: 42
          
          # # labels stale all issues except the ones with a Feature Request label
          # exempt-issue-labels: 'Feature Request'
          # days-before-stale: 182
          # days-before-close: 28
          
